export const dictionary = {
    // 簡單模式 (部分展示，實際建議放常見三、四字詞)
    "act": "行動", "add": "增加", "age": "年紀", "ago": "以前", "air": "空氣", "all": "全部", "and": "和", "ant": "螞蟻", "any": "任何", "apple": "蘋果", "arm": "手臂", "art": "藝術", "as": "當作", "ask": "問", "at": "在", "bad": "壞的", "bag": "袋子", "ball": "球", "bank": "銀行", "bar": "條/棒", "bat": "蝙蝠", "be": "是", "bed": "床", "bee": "蜜蜂", "big": "大的", "box": "箱子", "boy": "男孩", "bus": "公車", "but": "但是", "buy": "買", "by": "靠/由", "can": "能", "car": "車", "cat": "貓", "cup": "杯子", "cut": "切", "dad": "爸爸", "day": "天", "did": "做", "do": "做", "dog": "狗", "dot": "點", "dry": "乾的", "eat": "吃", "egg": "蛋", "end": "結束", "eye": "眼睛", "fan": "風扇", "far": "遠的", "fat": "胖的", "fly": "飛", "for": "為了", "get": "得到", "god": "神", "hat": "帽子", "he": "他", "hi": "嗨", "hot": "熱的", "how": "如何", "ice": "冰", "if": "如果", "in": "在內", "is": "是", "it": "它", "its": "它的", "jam": "果醬", "jet": "噴射機", "job": "工作", "joy": "歡樂", "key": "鑰匙", "kid": "小孩", "leg": "腿", "let": "讓", "lip": "嘴唇", "low": "低的", "map": "地圖", "may": "可能", "me": "我", "men": "男人們", "met": "遇見", "mix": "混合", "mom": "媽媽", "my": "我的", "net": "網", "new": "新的", "no": "不", "not": "不", "now": "現在", "off": "關閉", "oil": "油", "old": "老的", "on": "在上面", "one": "一", "out": "在外", "own": "擁有", "pen": "筆", "pet": "寵物", "pig": "豬", "pin": "針", "pot": "鍋子", "put": "放", "rat": "老鼠", "red": "紅色", "run": "跑", "sad": "傷心", "sea": "海", "see": "看見", "set": "設定", "she": "她", "sir": "先生", "sit": "坐", "six": "六", "sky": "天空", "so": "所以", "son": "兒子", "sun": "太陽", "tea": "茶", "ten": "十", "the": "這/那", "top": "頂部", "toy": "玩具", "try": "嘗試", "two": "二", "up": "向上", "us": "我們", "use": "使用", "way": "方法", "we": "我們", "wet": "濕的", "who": "誰", "why": "為什麼", "win": "贏", "yes": "是的", "you": "你",
    // ... 基礎與困難模式單字依此類推 ...
};

export const dict = {
    easy: ["act", "add", "age", "ago", "air", "all", "and", "ant", "any", "arm", "art", "ask", "bad", "bag", "ball", "bank", "bat", "bed", "bee", "big", "box", "boy", "bus", "but", "buy", "can", "car", "cat", "cup", "cut", "dad", "day", "dog", "dot", "dry", "eat", "egg", "end", "eye", "fan", "far", "fat", "fly", "get", "hat", "hot", "how", "ice", "jam", "jet", "job", "joy", "key", "kid", "leg", "let", "lip", "low", "map", "may", "men", "mix", "mom", "net", "new", "now", "oil", "old", "one", "own", "pen", "pet", "pig", "pin", "pot", "put", "rat", "red", "run", "sad", "sea", "set", "six", "sky", "son", "sun", "tea", "ten", "top", "toy", "two", "wet", "who", "win", "yes"],
    normal: ["Apple", "Banana", "Orange", "Mother", "Father", "School", "Flower", "Friend", "Yellow", "Window", "Kitchen", "Brother", "Sister", "Teacher", "Student", "Library", "English", "Morning", "Evening", "Welcome", "Healthy", "Weather", "Believe", "Careful", "Picture", "Holiday", "Country", "Kitchen", "Airport", "Station", "Traffic", "Perfect"],
    hard: ["Beautiful", "Different", "Dangerous", "Excellent", "Important", "Successful", "Wonderful", "Happen", "Experience", "Celebrate", "Christmas", "Knowledge", "Vegetable", "Restaurant", "Everything", "Basketball", "Dictionary", "Understand", "Chocolate", "Adventure", "Challenge", "Condition", "Education", "Equipment", "Environment"]
};
